sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gchalauri/docker-react .

script:
  - docker run -e CI=true gchalauri/docker-react npm run test


deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-153104230818"
    bucket_path: "docker-react"
    edge: true
    skip_cleanup: true
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"  

